spring.application.name=demo-config-dev


build.id=110001DEVgit
build.name=dev Build name git
build.version=dev Build Version git

PROPERTY_VALUE=Application config application property git
configFromProp=${CONFIG_FROM_PROPERTIES_VALUE_GIT}

